name: CI DevSecure API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t devsecure-api:latest .

      - name: Run container for testing
        run: |
          docker run -d -p 3000:3000 --name devsecure-api devsecure-api:latest
          sleep 5
          curl --fail http://localhost:3000 || (docker logs devsecure-api && exit 1)

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: devsecure-api:latest
          format: 'table'
          output: 'trivy-report.txt'

      # Snyk
      - name: Run Snyk to check Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: devsecure-api:latest
          args: --file=Dockerfile
          
      # GitLeaks
      - name: Run GitLeaks secret scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-path=gitleaks-report.json

      # Upload des rapports en artefacts
      - name: Upload scan reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            trivy-report.txt
            gitleaks-report.json

  push-docker:
    runs-on: ubuntu-latest
    needs: security-scan
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/devsecure-api:latest
          docker tag devsecure-api:latest $IMAGE_NAME
          docker push $IMAGE_NAME
